# Generated by Django 4.0.5 on 2022-06-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='board',
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
