# Generated by Django 4.0.5 on 2022-09-23 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectapp', '0002_remove_gamemodel_board_gamemodel_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='connected_player',
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='win',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='connected_players',
            field=models.ManyToManyField(blank=True, related_name='connected_players', to='connectapp.player'),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='active_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connectapp.player'),
        ),
    ]
