# Generated by Django 4.0.5 on 2022-09-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectapp', '0003_player_remove_gamemodel_connected_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_session',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
